"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i-@hldx$mi-ku1335u@0zsx%+tv+x^d7sc@5yy115hhi4%h==p'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True: Shows detailed error pages (development only)
# DEBUG = False: Hides sensitive information (production)
DEBUG = False

# ============================================================================
# Production vs Development Settings
# ============================================================================
# The following settings should be adjusted based on environment:
#
# DEVELOPMENT (HTTP):
#   - SECURE_SSL_REDIRECT = False
#   - SESSION_COOKIE_SECURE = False
#   - CSRF_COOKIE_SECURE = False
#   - DEBUG = True (for development)
#
# PRODUCTION (HTTPS):
#   - SECURE_SSL_REDIRECT = True
#   - SESSION_COOKIE_SECURE = True
#   - CSRF_COOKIE_SECURE = True
#   - DEBUG = False
#   - ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com']
#   - SECRET_KEY: Must be changed and kept secret
# ============================================================================

# ============================================================================
# HTTPS and SSL/TLS Configuration
# ============================================================================
# These settings enforce secure HTTPS connections and protect data in transit.
# IMPORTANT: These settings require HTTPS to be properly configured in your
# web server (Nginx, Apache, etc.) before enabling in production.

# HTTPS Redirect: Automatically redirect all HTTP requests to HTTPS
# Security: Prevents man-in-the-middle attacks by ensuring all traffic is encrypted
# WARNING: Only set to True when HTTPS is properly configured, otherwise
#          the site will be inaccessible (redirect loop)
SECURE_SSL_REDIRECT = False  # Set to True in production with HTTPS configured

# HTTP Strict Transport Security (HSTS): Instructs browsers to only connect via HTTPS
# Security: Prevents protocol downgrade attacks and cookie hijacking
# Value: Number of seconds browsers should remember to use HTTPS only
# 31536000 = 1 year (recommended for production)
SECURE_HSTS_SECONDS = 31536000  # 1 year

# HSTS Include Subdomains: Extends HSTS policy to all subdomains
# Security: Ensures all subdomains are also accessed via HTTPS
# WARNING: Only enable if ALL subdomains support HTTPS
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# HSTS Preload: Allows site to be included in browser HSTS preload lists
# Security: Provides additional protection by preloading HSTS policy
# Note: Requires manual submission to https://hstspreload.org/
SECURE_HSTS_PRELOAD = True

# Proxy SSL Header: Trust the X-Forwarded-Proto header from reverse proxy
# Security: When Django is behind a reverse proxy (Nginx, Apache, etc.) that
#          terminates SSL/TLS, this setting tells Django to trust the proxy's
#          X-Forwarded-Proto header to determine if the original request was HTTPS
# Format: (header_name, expected_value)
# WARNING: Only enable if you trust your reverse proxy, otherwise this can be
#          exploited to bypass HTTPS security checks
# IMPORTANT: Ensure your reverse proxy is properly configured to set this header
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ============================================================================
# Cookie Security Configuration
# ============================================================================
# These settings ensure cookies are only transmitted over secure HTTPS connections.

# Session Cookie Security: Only send session cookies over HTTPS
# Security: Prevents session hijacking via man-in-the-middle attacks
# WARNING: Set to True only when HTTPS is configured, otherwise users won't
#          be able to maintain sessions
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS

# CSRF Cookie Security: Only send CSRF cookies over HTTPS
# Security: Prevents CSRF token interception via man-in-the-middle attacks
# WARNING: Set to True only when HTTPS is configured
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS

# Session Cookie SameSite: Controls when cookies are sent with cross-site requests
# Options: 'Strict', 'Lax', or None
# 'Lax': Cookies sent with top-level navigations (recommended)
# 'Strict': Cookies never sent with cross-site requests (most secure)
SESSION_COOKIE_SAMESITE = 'Lax'

# CSRF Cookie SameSite: Controls CSRF cookie behavior with cross-site requests
CSRF_COOKIE_SAMESITE = 'Lax'

# ============================================================================
# Security Headers Configuration
# ============================================================================

# XSS Protection: Enable browser's built-in XSS filter
# Security: Provides an additional layer of XSS protection at the browser level
SECURE_BROWSER_XSS_FILTER = True

# Frame Options: Prevent clickjacking attacks
# Options: 'DENY' (no framing), 'SAMEORIGIN' (same origin only), or None
# Security: Prevents malicious sites from embedding your site in iframes
# 'DENY' is the most secure option
X_FRAME_OPTIONS = 'DENY'

# Content Type Sniffing: Prevent MIME type sniffing attacks
# Security: Prevents browsers from interpreting files as different MIME types
#          (e.g., preventing a text file from being executed as JavaScript)
SECURE_CONTENT_TYPE_NOSNIFF = True

# Referrer Policy: Controls how much referrer information is sent
# Options: 'no-referrer', 'same-origin', 'strict-origin-when-cross-origin', etc.
# Security: Prevents leaking sensitive information in referrer headers
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Content Security Policy (CSP) Settings
# CSP helps prevent XSS attacks by controlling which resources can be loaded
CSP_DEFAULT_SRC = "'self'"
CSP_SCRIPT_SRC = "'self' 'unsafe-inline'"  # 'unsafe-inline' needed for Django admin, remove in production if possible
CSP_STYLE_SRC = "'self' 'unsafe-inline'"  # 'unsafe-inline' needed for inline styles
CSP_IMG_SRC = "'self' data:"
CSP_FONT_SRC = "'self'"
CSP_CONNECT_SRC = "'self'"
CSP_FRAME_ANCESTORS = "'none'"  # Prevents embedding in frames (clickjacking protection)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf.apps.BookshelfConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Content Security Policy middleware (manually implemented)
    'LibraryProject.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'bookshelf.CustomUser'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
